import { APPEARANCE_DEFAULTS } from '../utils/theme.js';

export const EDITOR_AREAS = [
  { id: 'global', label: 'Header & Footer', icon: 'bi-window' },
  { id: 'home', label: 'Home', icon: 'bi-house' },
  { id: 'library', label: 'Library', icon: 'bi-collection' },
  { id: 'resource', label: 'Resource Page', icon: 'bi-file-earmark-text' },
  { id: 'download', label: 'Download Page', icon: 'bi-download' },
  { id: 'auth', label: 'Login & account pages', icon: 'bi-person-lock' },
];

const field = (area, group, key, label, type = 'text', defaultValue = '', extra = {}) => ({
  area,
  group,
  key,
  label,
  type,
  default: defaultValue,
  ...extra,
});

export const EDITOR_FIELDS = [
  // Global header, navigation, footer, and social presence.
  field('global', 'Brand', 'site_name', 'Site name', 'text', 'Jewish Educational Resources'),
  field(
    'global',
    'Brand',
    'site_tagline',
    'Site tagline',
    'text',
    'Jewish materials for early childhood education and schools',
  ),
  field('global', 'Brand', 'site_logo', 'Site logo', 'image', ''),
  field('global', 'Brand', 'site_logo_alt', 'Logo alternative text', 'text', 'Jewish Educational Resources'),
  field('global', 'Navigation', 'nav_series_label', 'Grades menu label', 'text', 'Grades'),
  field('global', 'Navigation', 'grade_levels', 'Grade choices', 'textarea', APPEARANCE_DEFAULTS.grade_levels),
  field('global', 'Navigation', 'nav_user_panel', 'Administrator link label', 'text', 'Dashboard'),
  field('global', 'Navigation', 'drawer_subjects_title', 'Mobile subjects label', 'text', 'Subjects'),
  field('global', 'Navigation', 'drawer_library_fallback', 'Mobile library label', 'text', 'Library'),
  field('global', 'Navigation', 'drawer_login_label', 'Mobile login label', 'text', 'Log in'),
  field('global', 'Navigation', 'drawer_signup_label', 'Mobile signup label', 'text', 'Sign up'),
  field('global', 'Navigation', 'nav_signup_label', 'Signup button label', 'text', 'Sign up'),
  field('global', 'Navigation', 'nav_login_label', 'Login button label', 'text', 'Log in'),
  field('global', 'Navigation', 'search_placeholder', 'Search placeholder', 'text', 'Search worksheets...'),
  field('global', 'Navigation', 'nav_subjects_label', 'Subjects menu label', 'text', 'Subjects'),
  field('global', 'Navigation', 'nav_types_label', 'Types menu label', 'text', 'Types'),
  field('global', 'Navigation', 'nav_more_label', 'More resources label', 'text', 'More resources'),
  field('global', 'Navigation', 'nav_featured_label', 'Featured label', 'text', 'Featured'),
  field('global', 'Footer', 'footer_subjects_title', 'Subjects heading', 'text', 'Subjects'),
  field('global', 'Footer', 'footer_resources_title', 'Resources heading', 'text', 'Resources'),
  field('global', 'Footer', 'footer_about_title', 'About heading', 'text', 'About'),
  field('global', 'Footer', 'footer_other_title', 'Other heading', 'text', 'Other'),
  field('global', 'Footer', 'footer_social_title', 'Social heading', 'text', 'Follow Us'),
  field('global', 'Footer', 'footer_link_library', 'Library link label', 'text', 'Library'),
  field('global', 'Footer', 'footer_link_free_signup', 'Signup link label', 'text', 'Free Signup'),
  field('global', 'Footer', 'footer_link_news', 'Updates link label', 'text', 'Updates'),
  field('global', 'Footer', 'footer_news_url', 'Updates link destination', 'url', ''),
  field('global', 'Footer', 'footer_link_membership', 'Membership link label', 'text', 'Membership'),
  field('global', 'Footer', 'footer_link_login', 'Login link label', 'text', 'Log in'),
  field('global', 'Footer', 'footer_link_account', 'Account link label', 'text', 'My account'),
  field('global', 'Footer', 'footer_link_terms', 'Terms link label', 'text', 'Terms of Use'),
  field('global', 'Footer', 'footer_terms_url', 'Terms link destination', 'url', ''),
  field('global', 'Footer', 'footer_link_privacy', 'Privacy link label', 'text', 'Privacy Policy'),
  field('global', 'Footer', 'footer_privacy_url', 'Privacy link destination', 'url', ''),
  field('global', 'Footer', 'footer_tagline', 'Footer description', 'textarea', APPEARANCE_DEFAULTS.footer_tagline),
  field('global', 'Footer', 'footer_copyright', 'Copyright suffix', 'text', APPEARANCE_DEFAULTS.footer_copyright),
  field('global', 'Footer', 'footer_show', 'Show footer', 'boolean', APPEARANCE_DEFAULTS.footer_show),
  field('global', 'Social links', 'social_facebook', 'Facebook URL', 'url', ''),
  field(
    'global',
    'Social links',
    'social_pinterest',
    'Pinterest URL',
    'url',
    'https://www.pinterest.com/jewisheducationalresources1/',
  ),
  field('global', 'Social links', 'social_instagram', 'Instagram URL', 'url', ''),
  field('global', 'Social links', 'social_youtube', 'YouTube URL', 'url', ''),

  // Home.
  field('home', 'Welcome section', 'home_intro_eyebrow', 'Small introduction', 'text', APPEARANCE_DEFAULTS.home_intro_eyebrow),
  field('home', 'Welcome section', 'home_intro_title', 'Main title', 'text', APPEARANCE_DEFAULTS.home_intro_title),
  field('home', 'Welcome section', 'home_intro_lead', 'Supporting text', 'textarea', APPEARANCE_DEFAULTS.home_intro_lead),
  field('home', 'Welcome section', 'home_intro_image', 'Main image', 'image', APPEARANCE_DEFAULTS.home_intro_image),
  field('home', 'Welcome section', 'home_intro_image_alt', 'Main image alternative text', 'text', APPEARANCE_DEFAULTS.home_intro_image_alt),
  field('home', 'Welcome section', 'home_intro_primary', 'Primary button label', 'text', 'Explore the library'),
  field('home', 'Welcome section', 'home_intro_primary_link', 'Primary button destination', 'url', '/library'),
  field('home', 'Welcome section', 'home_intro_primary_show', 'Show primary button', 'boolean', APPEARANCE_DEFAULTS.home_intro_primary_show),
  field('home', 'Welcome section', 'home_intro_secondary', 'Secondary button label', 'text', 'Create a free account'),
  field('home', 'Welcome section', 'home_intro_secondary_link', 'Secondary button destination', 'url', '/sign-up'),
  field('home', 'Welcome section', 'home_intro_secondary_show', 'Show secondary button', 'boolean', APPEARANCE_DEFAULTS.home_intro_secondary_show),
  field('home', 'Welcome section', 'home_intro_show', 'Show welcome section', 'boolean', APPEARANCE_DEFAULTS.home_intro_show),
  field('home', 'Hero', 'hero_title', 'Hero title', 'text', APPEARANCE_DEFAULTS.hero_title),
  field('home', 'Hero', 'hero_lead', 'Hero supporting text', 'textarea', APPEARANCE_DEFAULTS.hero_lead),
  field('home', 'Hero', 'home_hero_cta_primary', 'Primary button label', 'text', 'Explore library'),
  field('home', 'Hero', 'home_hero_cta_primary_link', 'Primary button destination', 'url', '/library'),
  field('home', 'Hero', 'home_hero_cta_primary_show', 'Show primary button', 'boolean', APPEARANCE_DEFAULTS.home_hero_cta_primary_show),
  field('home', 'Hero', 'home_hero_cta_secondary', 'Secondary button label', 'text', 'Create free account'),
  field('home', 'Hero', 'home_hero_cta_secondary_link', 'Secondary button destination', 'url', '/sign-up'),
  field('home', 'Hero', 'home_hero_cta_secondary_show', 'Show secondary button', 'boolean', APPEARANCE_DEFAULTS.home_hero_cta_secondary_show),
  field('home', 'Hero', 'hero_content_align', 'Hero alignment', 'select', APPEARANCE_DEFAULTS.hero_content_align, {
    options: [
      { value: 'left', label: 'Left' },
      { value: 'center', label: 'Center' },
      { value: 'right', label: 'Right' },
    ],
  }),
  field('home', 'Hero', 'home_hero_image', 'Hero image', 'image', '/images/hero/mascot-bear.png'),
  field('home', 'Hero', 'home_hero_image_alt', 'Hero image alternative text', 'text', 'Educational mascot'),
  field('home', 'Hero', 'home_hero_show', 'Show hero section', 'boolean', 'true'),
  field('home', 'Cards', 'home_card_worksheets_title', 'Worksheets card title', 'text', 'Worksheets'),
  field(
    'home',
    'Cards',
    'home_card_worksheets_desc',
    'Worksheets card description',
    'textarea',
    'Printable activity sheets for Hebrew, Torah and holidays.',
  ),
  field('home', 'Cards', 'home_card_materials_title', 'Materials card title', 'text', 'Materials'),
  field(
    'home',
    'Cards',
    'home_card_materials_desc',
    'Materials card description',
    'textarea',
    'PDFs, presentations and resources by category and age group.',
  ),
  field('home', 'Cards', 'home_card_account_title', 'Account card title', 'text', 'Free Account'),
  field(
    'home',
    'Cards',
    'home_card_account_desc',
    'Account card description',
    'textarea',
    'Sign up to save favorites and access the full library.',
  ),
  field('home', 'Sections', 'home_topics_title', 'Topics heading', 'text', 'Explore by topic'),
  field('home', 'Sections', 'home_topics_show', 'Show topics section', 'boolean', 'true'),
  field('home', 'Sections', 'home_featured_title', 'Featured heading', 'text', 'Featured this week'),
  field('home', 'Sections', 'home_featured_show', 'Show featured section', 'boolean', 'true'),
  field('home', 'Sections', 'section_recent_title', 'Recent materials heading', 'text', APPEARANCE_DEFAULTS.section_recent_title),
  field('home', 'Sections', 'home_recent_link', 'Recent materials link label', 'text', 'View all'),
  field('home', 'Sections', 'home_cards_show', 'Show library cards', 'boolean', 'true'),
  field('home', 'Sections', 'home_recent_show', 'Show recent materials', 'boolean', 'true'),
  field('home', 'Sections', 'home_prefooter_show', 'Show updates and guide', 'boolean', 'true'),
  field('home', 'Benefits', 'home_benefits_title', 'Benefits heading', 'text', 'Why use the library?'),
  field('home', 'Benefits', 'home_benefits_show', 'Show benefits section', 'boolean', 'true'),
  field('home', 'Benefits', 'home_benefit_1_title', 'Benefit 1 title', 'text', 'Instant download'),
  field('home', 'Benefits', 'home_benefit_1_text', 'Benefit 1 description', 'textarea', 'PDFs and ready-to-use worksheets to print or use on screen in just a few clicks.'),
  field('home', 'Benefits', 'home_benefit_2_title', 'Benefit 2 title', 'text', 'Organized by topic'),
  field('home', 'Benefits', 'home_benefit_2_text', 'Benefit 2 description', 'textarea', 'Hebrew, Torah, holidays, and activities organized by category.'),
  field('home', 'Benefits', 'home_benefit_3_title', 'Benefit 3 title', 'text', 'Made for educators'),
  field('home', 'Benefits', 'home_benefit_3_text', 'Benefit 3 description', 'textarea', 'Materials designed for Jewish schools, cheder, and families.'),
  field('home', 'Benefits', 'home_benefit_4_title', 'Benefit 4 title', 'text', 'Preview before downloading'),
  field('home', 'Benefits', 'home_benefit_4_text', 'Benefit 4 description', 'textarea', 'Open the PDF in the browser and download only what you need.'),
  field('home', 'Updates', 'home_blog_title', 'Updates heading', 'text', 'Library updates'),
  field('home', 'Free guide', 'home_ebook_title', 'Guide heading', 'text', 'Free guide'),
  field(
    'home',
    'Free guide',
    'home_ebook_lead',
    'Guide description',
    'textarea',
    'Download the guide for parents and educators: practical ideas to strengthen Jewish learning at home and school.',
  ),
  field('home', 'Free guide', 'home_ebook_cta', 'Guide button label', 'text', 'DOWNLOAD'),
  field('home', 'Free guide', 'home_ebook_url', 'Guide destination', 'url', '/library'),
  field('home', 'Contact', 'section_contact_title', 'Contact heading', 'text', APPEARANCE_DEFAULTS.section_contact_title),
  field('home', 'Contact', 'section_contact_lead', 'Contact supporting text', 'textarea', APPEARANCE_DEFAULTS.section_contact_lead),
  field('home', 'Contact', 'section_contact_image', 'Contact image', 'image', APPEARANCE_DEFAULTS.section_contact_image),
  field('home', 'Contact', 'section_contact_image_alt', 'Contact image alternative text', 'text', APPEARANCE_DEFAULTS.section_contact_image_alt),
  field('home', 'Contact', 'section_contact_background', 'Contact background image', 'image', APPEARANCE_DEFAULTS.section_contact_background),
  field('home', 'Contact', 'section_contact_bg_color', 'Contact background color', 'color', APPEARANCE_DEFAULTS.section_contact_bg_color),
  field('home', 'Contact', 'contact_name_label', 'Name field label', 'text', APPEARANCE_DEFAULTS.contact_name_label),
  field('home', 'Contact', 'contact_email_label', 'Email field label', 'text', APPEARANCE_DEFAULTS.contact_email_label),
  field('home', 'Contact', 'contact_message_label', 'Message field label', 'text', APPEARANCE_DEFAULTS.contact_message_label),
  field('home', 'Contact', 'home_contact_submit', 'Contact button label', 'text', 'Submit'),
  field('home', 'Contact', 'home_contact_show', 'Show contact section', 'boolean', 'false'),
  field('home', 'Topics', 'home_quick_topics', 'Quick topics (managed in Content)', 'json', APPEARANCE_DEFAULTS.home_quick_topics),

  // Library presentation copy. Resource data remains in the resource admin.
  field('library', 'Page', 'library_page_title', 'Library page title', 'text', 'Resource Library'),
  field('library', 'Page', 'library_page_subtitle', 'Library page subtitle', 'textarea', 'Find materials by subject, file type, and grade.'),
  field('library', 'Page', 'library_page_head_icon_show', 'Show library page icon', 'boolean', APPEARANCE_DEFAULTS.library_page_head_icon_show),
  field('library', 'Page', 'library_category_subtitle_show', 'Show subtitle below category name', 'boolean', APPEARANCE_DEFAULTS.library_category_subtitle_show),
  field('library', 'Page', 'library_root_catalog_show', 'Show all materials on the Library landing page', 'boolean', APPEARANCE_DEFAULTS.library_root_catalog_show),
  field('library', 'Search and filters', 'library_search_toggle_label', 'Search toggle label', 'text', 'Search and filter'),
  field('library', 'Search and filters', 'library_search_hide_label', 'Hide search label', 'text', 'Hide search'),
  field('library', 'Search and filters', 'library_search_label', 'Search field label', 'text', 'Search'),
  field('library', 'Search and filters', 'library_search_placeholder', 'Search placeholder', 'text', 'Title, description, or keyword...'),
  field('library', 'Search and filters', 'library_category_label', 'Category field label', 'text', 'Category'),
  field('library', 'Search and filters', 'library_all_categories_label', 'All categories label', 'text', 'All categories'),
  field('library', 'Search and filters', 'library_file_type_label', 'File type field label', 'text', 'File type'),
  field('library', 'Search and filters', 'library_grade_label', 'Grade field label', 'text', 'Grade'),
  field('library', 'Search and filters', 'library_all_grades_label', 'All grades label', 'text', 'All grades'),
  field('library', 'Search and filters', 'library_resource_type_label', 'Resource type field label', 'text', 'Resource type'),
  field('library', 'Search and filters', 'library_sort_label', 'Sort field label', 'text', 'Sort by'),
  field('library', 'Search and filters', 'library_access_label', 'Access field label', 'text', 'Access'),
  field('library', 'Search and filters', 'library_quick_filters_label', 'Quick filters label', 'text', 'Quick filters:'),
  field('library', 'Search and filters', 'library_filter_submit_label', 'Filter button label', 'text', 'Filter'),
  field('library', 'Search and filters', 'library_clear_filters_label', 'Clear filters label', 'text', 'Clear filters'),
  field('library', 'Search and filters', 'library_active_filters_label', 'Active filters label', 'text', 'Active filters:'),
  field('library', 'Results', 'library_subtopics_title', 'Subtopics heading', 'text', 'Subtopics:'),
  field('library', 'Results', 'library_subtopics_show', 'Show subtopics heading', 'boolean', APPEARANCE_DEFAULTS.library_subtopics_show),
  field('library', 'Results', 'library_results_title', 'Results heading', 'text', 'All materials:'),
  field('library', 'Results', 'library_materials_found_title', 'Filtered results heading', 'text', 'Materials found:'),
  field('library', 'Results', 'library_results_heading_show', 'Show results heading', 'boolean', APPEARANCE_DEFAULTS.library_results_heading_show),
  field('library', 'Results', 'library_material_types_show', 'Show material type cards', 'boolean', APPEARANCE_DEFAULTS.library_material_types_show),
  field('library', 'Results', 'library_progress_label', 'Progress label', 'text', 'Showing {shown} of {total} materials'),
  field('library', 'Results', 'library_load_more_label', 'Load more label', 'text', 'Load more materials'),
  field('library', 'Results', 'library_loading_label', 'Loading label', 'text', 'Loading materials...'),
  field('library', 'Results', 'library_view_slides_label', 'View slides label', 'text', 'View slides'),
  field('library', 'Results', 'library_download_label', 'Download label', 'text', 'Download'),
  field('library', 'Results', 'library_view_details_label', 'View details label', 'text', 'View details'),
  field('library', 'Results', 'library_retry_label', 'Retry label', 'text', 'Retry'),
  field('library', 'Results', 'library_empty_msg', 'Empty results message', 'text', 'No materials found.'),

  // Resource template.
  field('resource', 'Navigation', 'resource_breadcrumb_library', 'Library breadcrumb', 'text', 'Library'),
  field('resource', 'Navigation', 'resource_materials_sidebar_title', 'Materials sidebar title', 'text', 'Materials'),
  field('resource', 'Content', 'resource_preview_pdf_label', 'PDF preview label', 'text', 'PDF document'),
  field('resource', 'Content', 'resource_preview_presentation_label', 'Presentation preview label', 'text', 'Presentation (PPTX)'),
  field('resource', 'Content', 'resource_more_pages_label', 'More pages label', 'text', 'More pages'),
  field('resource', 'Content', 'resource_gallery_label', 'Gallery label', 'text', 'Pages'),
  field('resource', 'Actions', 'resource_download_label', 'Download action label', 'text', 'Download'),
  field('resource', 'Actions', 'resource_full_pdf_label', 'Full PDF action label', 'text', 'Full PDF (Premium)'),
  field('resource', 'Actions', 'resource_preview_label', 'Preview action label', 'text', 'Preview'),
  field('resource', 'Actions', 'resource_favorite_label', 'Favorite action label', 'text', 'Save to my list'),

  // Download template.
  field('download', 'Navigation', 'download_breadcrumb_library', 'Library breadcrumb', 'text', 'Library'),
  field('download', 'Navigation', 'download_breadcrumb_current', 'Current breadcrumb', 'text', 'Download'),
  field('download', 'Messages', 'download_lead', 'Download supporting text', 'textarea', 'Your file is ready.'),
  field('download', 'Messages', 'download_file_fallback', 'File fallback label', 'text', 'File'),
  field('download', 'Messages', 'download_quota_label', 'Quota label', 'text', 'Downloads remaining: {remaining} of {max} {period}.'),
  field('download', 'Actions', 'download_button_label', 'Download button label', 'text', 'Download file'),
  field('download', 'Actions', 'download_back_to_material_cta', 'Back to resource label', 'text', 'Back to resource'),
  field('download', 'Actions', 'download_error_back_cta', 'Error back label', 'text', 'Back to library'),

  // Account screens. Security/error messages are intentionally not editable;
  // these keys cover only the visual copy around the protected forms.
  field('auth', 'Login', 'auth_login_title', 'Login title', 'text', 'Welcome back'),
  field('auth', 'Login', 'auth_login_lead', 'Login supporting text', 'textarea', 'Sign in to your account to access the library'),
  field('auth', 'Login', 'auth_google_login_label', 'Google login button', 'text', 'Continue with Google'),
  field('auth', 'Login', 'auth_or_label', 'Alternative login separator', 'text', 'or'),
  field('auth', 'Login', 'auth_full_name_label', 'Full name label', 'text', 'Full Name'),
  field('auth', 'Login', 'auth_email_label', 'Email label', 'text', 'Email address'),
  field('auth', 'Login', 'auth_password_label', 'Password label', 'text', 'Password'),
  field('auth', 'Login', 'auth_login_button', 'Login button', 'text', 'Log in'),
  field('auth', 'Login', 'auth_forgot_link', 'Forgot password link', 'text', 'Forgot password?'),
  field('auth', 'Login', 'auth_signup_link', 'Signup link', 'text', 'Sign up free'),
  field('auth', 'Signup', 'auth_signup_title', 'Signup title', 'text', 'Create Account'),
  field('auth', 'Signup', 'auth_signup_lead', 'Signup supporting text', 'textarea', 'Sign up to access all materials'),
  field('auth', 'Signup', 'auth_google_signup_label', 'Google signup button', 'text', 'Sign up with Google'),
  field('auth', 'Signup', 'auth_signup_button', 'Signup button', 'text', 'Sign Up Free'),
  field('auth', 'Signup', 'auth_existing_account', 'Existing account prompt', 'text', 'Already have an account?'),
  field('auth', 'Signup', 'auth_login_link', 'Login link', 'text', 'Log in'),
  field('auth', 'Signup', 'auth_password_hint', 'Password hint', 'text', 'Minimum 6 characters'),
  field('auth', 'Recovery', 'auth_recovery_title', 'Recovery title', 'text', 'Reset Password'),
  field('auth', 'Recovery', 'auth_recovery_lead', 'Recovery supporting text', 'textarea', 'We will send a reset link to your email'),
  field('auth', 'Recovery', 'auth_send_reset_button', 'Send reset button', 'text', 'Send Reset Link'),
  field('auth', 'Recovery', 'auth_back_login_link', 'Back to login link', 'text', 'Back to Log in'),
  field('auth', 'Reset', 'auth_new_password_title', 'New password title', 'text', 'New password'),
  field('auth', 'Reset', 'auth_new_password_lead', 'New password supporting text', 'textarea', 'Choose a secure password'),
  field('auth', 'Reset', 'auth_confirm_password_label', 'Confirm password label', 'text', 'Confirm password'),
  field('auth', 'Reset', 'auth_save_password_button', 'Save password button', 'text', 'Reset password'),
];

const FIELD_INDEX = new Map(EDITOR_FIELDS.map((item) => [item.key, item]));

export function fieldsForArea(area) {
  return EDITOR_FIELDS.filter((item) => item.area === area);
}

export function fieldByKey(key) {
  return FIELD_INDEX.get(key) || null;
}

export function normalizeEditorUrl(value) {
  const input = String(value ?? '').trim();
  if (!input) return '';
  if (input.startsWith('/') && !input.startsWith('//')) return input;
  if (/^(mailto:|tel:)/i.test(input)) return input;
  try {
    const parsed = new URL(input);
    return parsed.protocol === 'https:' ? parsed.toString() : null;
  } catch {
    return null;
  }
}
